// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpnaaaocqqmkslwqrkyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwbmFhYW9jcXFta3Nsd3Fya3lkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwOTExMDMsImV4cCI6MjA2NDY2NzEwM30.tmK-tjqFcHS8oVEOwqrCfkhDN1-fS9uIZ6JrtLSobi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);